### ISSUE TITLE
upgrade from 2.0.4 to 2.0.5 - window is not defined

### ISSUE THREAD

**Issue by colbyfayock** [dweirich/gatsby-plugin-react-leaflet#8]
Hiya, started getting an issue on 2.0.5 with the latest:
![image](https://user-images.githubusercontent.com/1045274/58287079-287ad280-7d7e-11e9-875d-48438b0eedab.png)

it looks similar to past issues. no code changes from 2.0.4, rolling back to it fixes the issue so will carry on with that for now

i'll try to see if i can find time to repro it in a clean repo, but hoping something immediately stands out for you.

thanks

**Comment by dweirich** [comment]
@colbyfayock Sorry about that, looks like I got a piece of the webpack config mixed up in that last push. Just added a fix for it.

**Comment by colbyfayock** [comment]
no worries! and thanks for jumping on it quick. still looks to be failing though on 2.0.6 :(

![image](https://user-images.githubusercontent.com/1045274/58288686-58c47000-7d82-11e9-8d0d-6bea3062d6b8.png)

**Comment by dweirich** [comment]
I believe the problem is that the library is looking specifically for `/node_modules/leaflet` and `/node_modules/react-leaflet`. Your error message shows a leaflet file being called at `/lib/fogg/src/lib/leaflet.js`. I've pushed a change to make it look for leaflet in deeper sub-directories of `node_modules`.

**Comment by colbyfayock** [comment]
:( still didn't fix it. before you try digging in again, ill try to find the time to get this reproed in a clean repo.

to provide a little clarity on that file you mentioned, leaflet.js isn't leaflet itself, it's a file that contains some helper functions that imports leaflet within it.

thanks for looking at this

**Comment by dweirich** [comment]
Just tried testing from the remote npm package rather than the local package I had and discovered a dumb error on my part. This should work now.

**Comment by colbyfayock** [comment]
ah haha, well that fixed that issue but now i have a new error 🤕 though looks like this might be due to a library im using and might not anything to do with this plugin. still odd it worked before

https://github.com/kartena/Proj4Leaflet

![image](https://user-images.githubusercontent.com/1045274/58343125-4d278680-7e20-11e9-9a04-5b7dd434fef5.png)

really do appreciate the help here. thank you!

**Comment by dweirich** [comment]
@colbyfayock no problem! The package is looking specifically for something like `/node_modules/leaflet` or `/node_modules/react-leaflet` now. Before it was just looking for any library with the word `leaflet` in its path. It could be that before it was also catching and nulling the `proj4leaflet` library since it has leaflet in the name. Try adding this to your gastby-node.js file:

```
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /proj4leaflet/,
            use: loaders.null()
          }
        ]
      }
    })
  }
}
```

**Comment by colbyfayock** [comment]
Sorry only now getting around to this, but wanted to add another thank you! 😄🍻
